### ISSUE TITLE
Component library reuse requires CSS or SCSS TSC to compile without copying the compiled style file

### ISSUE THREAD

**Issue by DreamPWJ** [wixplosives/sample-monorepo#169]
![image](https://user-images.githubusercontent.com/16730031/102971296-1b166300-4534-11eb-9972-0c40086d39a2.png)

**Comment by AviVahl** [comment]
Thank you for bringing this up.

I aimed to avoid showcasing styling solutions in this repository. I did add a naive css extraction webpack setup for the `sanitize.css`, but it doesn't have any asset copying (into `dist`) so it doesn't really support local css assets.

The thing is... each styling solution has its own set of requirements.

CSS-in-JS based solutions, for example, probably won't need to worry about it at all.

Within Wix, we use [Stylable](https://github.com/wix/stylable), which has its own CLI (`stc`) to build and/or copy `.st.css` files into `dist`.

Full support for source code importing `.css/.scss/.less/.whatever` requires additional building. It would have to be addressed for Node as well, if one wants to execute mocha on tests importing these source files.

Because of the above, I tend to view this as currently out of the scope for this repository. I'll probably add a note in the README explaining this.

Having said all that, you could probably write a short asset copying script to build/copy `.css` assets from `src` to `dist`. If there's specific assistance you need, please let me know.
