### ISSUE TITLE
Components with React as Peer Dependency

### ISSUE THREAD

**Issue by skulptur** [wixplosives/sample-monorepo#3]
This is more of a question, but won't React be bundled twice in this setup since both components and app depend on React? Or as long as the version is identical they will use the same?

Either way, components should have React as peer dep. so you could potentially publish it as a package and use in other projects:
https://yarnpkg.com/blog/2018/04/18/dependencies-done-right/

I'm mainly asking because when I tried doing a monorepo with peer deps. I encountered a problem with React not resolving properly.

**Comment by AviVahl** [comment]
Behavior-wise, as long as:
1. all `react` version requests (in `package.json` files) resolve to the same version.
2. the package manager used on user-end dedupes packages correctly (latest yarn/npm usually do).

Then only a single version would exist on user end.

Since both points break easily, and things become more complex when lock files are involved (on user's end), `peerDependency` is indeed the correct solution here.

I'll update the repository. Thanks for bringing this up.
