### ISSUE TITLE
scripts do not respect dependency order

### ISSUE THREAD

**Issue by joshclow** [wixplosives/sample-monorepo#5]
In the readme, it says 
```Automatically ensures order when using lerna run [script], meaning that if package-a depends on package-b, it will run package-b's scripts first.```

But this does not actually appear to happen. For example, if I delay the build of components (by changing its build script to something like `sleep 10 && ts-build...`) it clearly completes well after app's build script runs. In fact, it looks like when I do that, what actually happens is that app searches the directory for `index.ts` in `src` and then uses that to get type information. If I change the `src` directory to another name (and update `ts-build` to reference that instead of `src`), then app fails to build unless I take the `sleep 10` out, at which point it may build because components builds pretty quickly. 

Not a huge issue, but I found this repo because I was trying to pin down if Lerna actually *does* use its dependency graph to make sure scripts complete where dependencies are involved and hoped that this sample demonstrated that it did.

**Comment by AviVahl** [comment]
I think the real issue is that the README does not mention the source-to-source changes.
The idea was to be able to run the build/test scripts of any package without having the built the dependent packages within the mono-repo.

The mapping to `/src` is done via `tsconfig.base.json`'s "paths" field. If you rename it, you also have to change that. There's special support in both `@ts-tools/node` and `@ts-tools/webpack-loader` to work out of the box with "paths" (it remaps imports using typescript's resolution result). Also worth noting is that `@ts-tools/build` (`ts-build`) is used instead of `tsc` so that the "paths" mapping won't mess up the `outDir` structure. It also has the benefit of building both module targets in a single run.

Since adding source-to-source, I've changed the root built/test scripts to have the `--parallel` flag.

I hope this makes things a bit clearer. I'll try to get this info into the `README`.

**Comment by joshclow** [comment]
Thanks for the clarification!
