### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by j** [wixplosives/sample-monorepo#8]
How do you go about packaging & deployment with this structure?

**Comment by amir-arad** [comment]
see [here](https://github.com/wixplosives/sample-monorepo/blob/master/packages/app/package.json#L12)

**Comment by AviVahl** [comment]
Standard lerna publishing. Nothing customized further.

To publish new versions of the packages to npm:
`yarn lerna publish`

Lerna asks for new version numbers for packages that changed since last release (and their dependencies). Every package has a `prepack` script which automatically runs `build` right before packing.

To force a release of all packages (regardless of which packages changed):
`yarn lerna publish --force-publish` 

It should also be noted that custom automated publishing can be added. For example, in [file-services](https://github.com/wixplosives/file-services), which is based on this setup, a custom cli called `lerna-publisher` [is used](https://github.com/wixplosives/file-services/blob/master/.github/workflows/npm.yml) to automatically publish from CI when `master` has unpublished version bumps. All I do is `yarn lerna version` (or `yarn lerna version --force-publish`), which bumps versions and CI does the rest of the publishing.

Deployment of app/server assets (build script linked by @amir-arad) to any production server is not shown in this repo, as it depends on how your production is set up, and what kind of packages your repo holds.
